

# User Settings
username: Exploradores
user_description: Sergio Carrillo Sánchez
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: JoseLuisManzanaresRivera
facebook_username: Exploradores-124737764353663
twitter_username: JLManzanaresR
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji


# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
